### ISSUE TITLE
Something is not right, unable to get it running

### ISSUE THREAD

**Issue by gaurav-nelson** [pszuster/OpenshiftTemplateEditor#2]
I followed the instructions but I am unable to get this running. It just keeps loading items from GitHub forever...
![tempedit](https://user-images.githubusercontent.com/23069445/37501181-db5d08ca-2918-11e8-8668-950db8717d39.gif)

**Comment by pszuster** [comment]
That is strange, I've just tested it again with Chrome and Firefox and works ok. It takes a while when it opens up because it is only an html, all the dependencies (javascript libraries, json schemas, images) are downloaded upon starting.

**Comment by gaurav-nelson** [comment]
Firefox on Windows 10 (it keeps loading indefinitely)

**Comment by pszuster** [comment]
Are you able to download the files from the browser? Could be possible that you are behind a firewall or some restricted network? I've heard of company networks restricting github raw content download.

**Comment by hodrigohamalho** [comment]
@gaurav-nelson could you test it again ? I think it was solved.

Regards

**Comment by gaurav-nelson** [comment]
Thanks @hodrigohamalho It seems to run fine now. Closing this issue.
