### ISSUE TITLE
Takes ages to load

### ISSUE THREAD

**Issue by Vad1mo** [pszuster/OpenshiftTemplateEditor#3]
the index.html take ages to load almost freezes.
I think it has to do with loading content from git. I think everything should be replaced with rawgit.

This screenshot show the time to load just the index.html page.
![image](https://user-images.githubusercontent.com/1492007/38026876-0bcc6d7e-328e-11e8-96ce-fad4d9efb18a.png)

**Comment by pszuster** [comment]
Takes a lot of time because it downloads everything each time. In a next iteration I'm planning to convert it into a web app with all the dependencies included locally..

**Comment by hodrigohamalho** [comment]
@Vad1mo could you test it again ? I think it was improved with my PR.

regards

**Comment by hodrigohamalho** [comment]
@pszuster i think you can close this one.
