### ISSUE TITLE
spinning wheel after updating to v3.9 schema

### ISSUE THREAD

**Issue by vap0rtranz** [pszuster/OpenshiftTemplateEditor#6]
I've pulled v3.9 schema from Github: https://github.com/openshift/origin/blob/release-3.9/api/swagger-spec/openshift-openapi-spec.json, then imported JSON via https://github.com/garethr/openapi2jsonschema, and added v3.9 as option to my local HTML.  Loading of v3.7 works as expected.

After selecting "3.9" from dropdown in HTML, the server instance appears to hang on last schema import and the browser sits with spinning wheel.

Browsers:
Firefox 52.7.2 on Linux
Chrome 65.0.3325.181 on Linux

```
127.0.0.1 - - [04/Jun/2018 12:45:45] "GET /schemas/v3.9/volumeprojection.json HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 12:45:45] "GET /schemas/v3.9/vspherevirtualdiskvolumesource.json HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 12:45:45] "GET /schemas/v3.9/watchevent.json HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 12:45:45] "GET /schemas/v3.9/webhookclientconfig.json HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 12:45:45] "GET /schemas/v3.9/webhook.json HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 12:45:45] "GET /schemas/v3.9/webhooktrigger.json HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2018 12:45:46] "GET /schemas/v3.9/weightedpodaffinityterm.json HTTP/1.1" 200 -

```

**Comment by pszuster** [comment]
I've uploaded v3.9 schemas, it should work fine now

**Comment by vap0rtranz** [comment]
Yes latest update loads 3.9 now. ty!
